[project]
name = "bitbucket-snippets-to-bookstack"
version = "0.1.0"
requires-python = ">=3.7"
dependencies = [
    "requests",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
